### ISSUE TITLE
How do I remove this from my terminal?

### ISSUE THREAD

**Issue by zer02z** [remo7777/T-Header#11]
please tell how to remove the t-header from my terminal.

when viewing from vnc, it becomes an error

**Comment by anonymousdarkarmy** [comment]
rm-rf t header

**Comment by remo7777** [comment]
> please tell how to remove the t-header from my terminal.
> 
> when viewing from vnc, it becomes an error

```chsh -s bash;apt remove zsh -y;rm -rf ~/.oh-my-zsh ~/.plugins ~/.zsh*;exit;```

**Comment by Diadi01** [comment]
> > please tell how to remove the t-header from my terminal.
> > when viewing from vnc, it becomes an error
> 
> `chsh -s bash;apt remove zsh -y;rm -rf ~/.oh-my-zsh ~/.plugins ~/.zsh*;exit;`

Not working

**Comment by remo7777** [comment]
`cd ~/T-Header && bash t-header.sh --remove && exit`
