### ISSUE TITLE
Usage: lolcat [<options>] [file ...]  lolcat: error: no such option: -t

### ISSUE THREAD

**Issue by loyalabhi** [remo7777/T-Header#12]
![Screenshot_2020-12-22-17-22-06-433_com termux](https://user-images.githubusercontent.com/68819095/102886023-581e1f00-447a-11eb-9d55-c570cedff38a.jpg)
What is the problem for the above error to show up..?

**Comment by nickoardhana** [comment]
Same problem, how to fix this?

**Comment by Yuth-AN** [comment]
gem install lolcat

**Comment by D3m0ni4k** [comment]
gem install lolcat lmao 🤣
