### ISSUE TITLE
Remove T-Header

### ISSUE THREAD

**Issue by Diadi01** [remo7777/T-Header#16]
`rm -rf ~/.oh-my-zsh ~/.termux ~/.zshrc; mv ~/.termux.* ~/.termux` not working

**Comment by Dubeycoder-Kaushalt96** [comment]
How to remove our t-header from my termux....

**Comment by m-society-0-0** [comment]
Please how to remove

**Comment by Diadi01** [comment]
> Please how to remove

I don't know man

**Comment by remo7777** [comment]
`cd ~/T-Header && bash t-header.sh --remove && exit`
