### ISSUE TITLE
How to remove it …?

### ISSUE THREAD

**Issue by kushnamdev** [remo7777/T-Header#2]
How to remove it from my terminal?

**Comment by remo7777** [comment]
rm -rf ~/.oh-my-zsh ~/.termux ~/.zshrc; mv ~/.termux.* ~/.termux

**Comment by mujeebrahman23** [comment]
How to reset to default

**Comment by asfand1891** [comment]
remove command not working

**Comment by Diadi01** [comment]
Remove command not working

**Comment by Diadi01** [comment]
> Remove command not working

┌─[Diadi@termux]─[~]
└──╼ ❯❯❯ rm -rf ~/.oh-my-zsh ~/.termux ~/.zshrc; mv ~/.termux.* ~/.termux;
mv: cannot stat '/data/data/com.termux/files/home/.termux.*': No such file or directory

┌─[Diadi@termux]─[~]
└──╼ ❯❯❯

**Comment by Rajeev0007** [comment]
> `rm -rf ~/.oh-my-zsh ~/.termux ~/.zshrc; mv ~/.termux.* ~/.termux;` copy paste on termux cmd

Not work

**Comment by thrisha24** [comment]
> rm -rf T-Header

> exit

**Comment by fadedmagician** [comment]
> For remove tool `cd ~/T-header && bash t-header.sh --remove && exit`

**Comment by fadedmagician** [comment]
For remove tool `cd ~/T-header && bash t-header.sh --remove && exit`
