### ISSUE TITLE
How to Remove

### ISSUE THREAD

**Issue by m-society-0-0** [remo7777/T-Header#20]
Please help .. how remove

**Comment by fikrado** [comment]
You can remove it by installing new termux shell try this github.com/fikrado/qurxin you can also get the documents on how to install or remove it 

All the best

**Comment by m-society-0-0** [comment]
Nhi hui yar ...

**Comment by kafidrenaldo** [comment]
> Anda dapat menghapusnya dengan menginstal shell termux baru coba ini github.com/fikrado/qurxin Anda juga bisa mendapatkan dokumen tentang cara menginstal atau menghapusnya
> 
> Semua yang terbaik

Tapi saya kok gk bisa bang

**Comment by remo7777** [comment]
`cd ~/T-Header && bash t-header.sh --remove && exit`
