### ISSUE TITLE
Erasing "suscribe ..."

### ISSUE THREAD

**Issue by arnauldb** [remo7777/T-Header#3]
Hello,

How can I get rid off of the "suscribe to my youtube channel" banner?

Thank you.

**Comment by remo7777** [comment]
yes it can be change by editing `~/.zshrc`
you have see end of two or three line hv mentioned that text "suscribe to my youtube channel" just delete that line

**Comment by moneer082** [comment]
How can i enter the command and can i change the color thanks in advance.

**Comment by remo7777** [comment]
https://github.com/remo7777/T-Header/issues/4#issue-543416106

**Comment by remo7777** [comment]
check on new issue or contact me on telegram 
Here we'll try to solve problems related to your termux as soon as possible

Group link: https://t.me/joinchat/FY2amVKlBrBQIi3dT_lUug
